const shoes = [
  {
    name: "Air Force 1",
    brand: "Nike",
    img: "https://example.com/airforce1.jpg",
    price: 120,
    alt: "White Nike Air Force 1 sneaker",
  },
  {
    name: "Air Max 90",
    brand: "Nike",
    img: "https://example.com/airmax90.jpg",
    alt: "White and black Nike Air Max 90 sneaker",
    price: 150,
  },
  {
    name: "Air Zoom Pegasus 37",
    brand: "Nike",
    img: "https://example.com/pegasus37.jpg",
    price: 90,
    alt: "White Nike Air Zoom Pegasus 37 sneaker",
  },
  {
    name: "Adidas Ultraboost 21",
    brand: "Adidas",
    img: "https://example.com/ultraboost21.jpg",
    price: 210,
    alt: "Black Adidas Ultraboost 21 sneaker",
  },
  {
    name: "Adidas Stan Smith",
    brand: "Adidas",
    img: "https://example.com/stan-smith.jpg",
    price: 150,
    alt: "White Adidas Stan Smith sneaker",
  },
  {
    name: "Converse Chuck",
    brand: "Converse",
    img: "https://example.com/converse-chuck.jpg",
    alt: "White Converse Chuck Taylor All Star sneaker",
    price: 85,
  },
  {
    name: "Taylor All Star",
    brand: "Converse",
    img: "https://example.com/taylor-all-star.jpg",
    price: 95,
    alt: "White Converse Taylor All Star sneaker",
  },
  {
    name: "New Balance 574",
    brand: "New Balance",
    img: "https://example.com/new-balance-574.jpg",
    price: 80,
    alt: "Grey New Balance 574 sneaker",
  },
  {
    name: "New Balance 990v5",
    brand: "New Balance",
    img: "https://example.com/new-balance-990v5.jpg",
    price: 175,
    alt: "Grey New Balance 990v5 sneaker",
  },
  {
    name: "Vans Old Skool",
    brand: "Vans",
    img: "https://example.com/vans-old-skool.jpg",
    price: 70,
    alt: "Black Vans Old Skool sneaker",
  },
  {
    name: "Puma Suede Classic",
    brand: "Puma",
    img: "https://example.com/puma-suede-classic.jpg",
    price: 120,
    alt: "Black Puma Suede Classic sneaker",
  },
  {
    name: "Asics Gel-Kayano 27",
    brand: "Asics",
    img: "https://example.com/asics-gel-kayano-27.jpg",
    price: 130,
    alt: "Black Asics Gel-Kayano 27 sneaker",
  },
  {
    name: "Adidas Samba OG",
    brand: "Adidas",
    img: "https://example.com/samba-og.jpg",
    price: 120,
    alt: "Black Adidas Samba OG sneaker",
  },
  {
    name: "Adidas Samba XLG 'Blue'",
    brand: "Adidas",
    img: "https://example.com/xlgblue.jpg",
    price: 120,
    alt: "Blue Adidas XLG sneaker",
  },
  {
    name: "Classic Watercolored Marbled Clog",
    brand: "Crocs",
    img: "https://example.com/classicwatercoloredmarbledclog.jpg",
    price: 120,
    alt: "Classic Watercolored Marbled Crocs",
  },
  {
    name: "Birkenstock Boston Soft Footbed Suede",
    brand: "Birkenstock",
    img: "https://example.com/birkenstockboston.jpg",
    price: 120,
    alt: "Birkenstock Boston Soft Footbed Suede Berks",
  },
  {
    name: "Air Max 90",
    brand: "Nike",
    price: 120,
  },
  {
    name: "Air Max 90",
    brand: "Nike",
    price: 120,
  },
  {
    name: "Air Max 90",
    brand: "Nike",
    price: 120,
  },
  {
    name: "Air Max 90",
    brand: "Nike",
    price: 120,
  },
];
